### PR TITLE
[Data Tables] Migrate table service to pipeline architecture

### PR DESCRIPTION
**Pull request by ShayMusachanov-dev**
Before I continue implementing the missing features, could someone please verify that I am up to date with the latest changes in the architecture?

### CODE REVIEW

**Comment by rylev** [comment]
@ShayMusachanov-dev sorry that we let this sit for so long. Would you still be interested in working on this? If so, would you be able to rebase? Then we can give this an initial review.

**Comment by rylev** [comment]
> In general, azure_data_cosmos is the most up-to-date implementation I can refer to, right?

Yes that is correct.

**Comment by ShayMusachanov-dev** [comment]
> It looks like the rebase was not successful (there are a lot of comments that are not yours on this branch). Can you try again. You need to rebase against this fork's `main` branch.

I implemented the basic operations of the table service client (create, delete, and query), and I have a couple of questions.
But before we move on, can you please verify I did the rebase correctly this time?

**Comment by rylev** [comment]
@ShayMusachanov-dev I'm really sorry we couldn't get your changes in. It was quite hard to coordinate how to get these changes in with the other changes that were being made. To that end #874 supersedes these changes (but gives a shout out to the work you've done here!).

**Pull request closed without merging**
