### PR TITLE
Refactor pipeline operation dispatch

### PR DESCRIPTION
**Pull request by rylev**
This is an attempt to clean up the dispatching of pipeline operations. Unfortunately, it doesn't really save very much on *lines* of code, but it is less code overall. 

Abstracting over the stream code has proven to be quite difficult, and is likely impossible without resorting to dynamic dispatch and adding some traits for things.

### CODE REVIEW

**Review by MindFlavor — APPROVED** [review]
I think it's an _excellent_ change. I really like new function `run_pipeline`: it makes very easy and error proof to implement new client functions. 

@ryan: What do you think about including the `XXXResponse::try_from(response)` in `run_pipeline` as well? It would make even easier to implement client functionalities _and_ force new implementations to follow the pattern we are now using (compose pipeline -> execute it -> convert result to specific response struct).

**Comment by rylev** [comment]
@MindFlavor I pushed a change that does just that. This requires that we crate a new trait which I've modeled directly after the std lib's `TryFrom` trait.

**Review by yoshuawuyts — APPROVED** [review]

**Comment by MindFlavor** [comment]
> @MindFlavor I pushed a change that does just that. This requires that we crate a new trait which I've modeled directly after the std lib's `TryFrom` trait.

It's beautiful! ❤️❤️

**Review by cataggar — APPROVED** [review]

**Comment by cataggar** [comment]
@rylev, can we merge this?

**Comment by rylev** [comment]
I'm not fully happy with this solution as we end up actually with *more* code than before. I'm going to close this for now and explore it in a different PR.

**Pull request closed without merging**
