### PR TITLE
Remove default features of http-types

### PR DESCRIPTION
**Pull request by omid**

### CODE REVIEW

**Comment by heaths** [comment]
Can you explain why?

**Review by heaths — CHANGES_REQUESTED** [review]
Please provide a reason as to why this change is necessary or recommended.

**Comment by omid** [comment]
@heaths I'm not familiar with the source code that much, so my change can break the lib, but at least the tests I run passes.

I use azure sdk in a project and saw useless (to me!) and old dependencies which are attached to the not-actively-maintained `http-types`. And this change is to avoid including them, if I understood correctly.

**Comment by omid** [comment]
OK, now I investigated more :/

`http-types` has some 3-year-old changes on `master` which are not yet released! So my change here is meaningless and wrong!

Rust ecosystem should think about this old `http-types` package with ~10M downloads!

**Comment by svix-jplatte** [comment]
Related: #1644

**Pull request closed without merging**
