### PR TITLE
Add `setters` macro

### PR DESCRIPTION
**Pull request by rylev**
This might not be worth it, but I decided to play around with creating a macro_rules macro for declaring setters in request builders. This reduces the amount of repetition. I only implemented this for a few builders but you should get a sense of what this will look like across all the builders. 

Setters are now declared like this:
```rust
setters! {
  user_agent: &'a str => Some(UserAgent::new(user_agent)),
  activity_id: &'a str => Some(ActivityId::new(activity_id)),
  consistency_level: ConsistencyLevel => Some(consistency_level),
}
```

I also removed the private getters since they're not really needed. 

This removes nearly 2000 lines of code.

### CODE REVIEW

**Comment by rylev** [comment]
@MindFlavor Thoughts on this?

**Comment by MindFlavor** [comment]
I really like it, it makes the code much more lean and manageable. I also agree that getters are not needed in request builders, further simplifying the code.

Great work 🥇 !

**Comment by rylev** [comment]
@MindFlavor this is ready for review!

**Review by ctaggart — APPROVED** [review]
Looks good to me.

**Pull request merged**
