### PR TITLE
implement federated_credential_flow and workload_identity_creds and add them to the environment_credential

### LINKED ISSUE #1305: Feature: Support kubernetes workload identities
Current workaround is to use an init container with 

```bash
az login --service-principal -u $AZURE_CLIENT_ID --allow-no-subscriptions -t $AZURE_TENANT_ID --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE) &&
az account get-access-token --query 'accessToken' --resource https://storage.azure.com --output tsv > /tmp/az-access-token.json  &&
cat /tmp/az-access-token.json
```

Code in Application:

```rust
    let bearer_token = std::env::var("BEARER_TOKEN").expect("BEARER_TOKEN not set");
    let storage_credentials = StorageCredentials::BearerToken(bearer_token);
```

Would be realy nice if the DefaultCredential would support this login flow.
If someone guides me where and how to do it, i would like to contribute and create a PR.

BR Simon

### PR DESCRIPTION
**Pull request by simon-an**
fixes #1305

### CODE REVIEW

**Comment by simon-an** [comment]
@microsoft-github-policy-service agree

**Review by heaths — CHANGES_REQUESTED** [review]
Why does the environment_credential not work? Can we not fix that? In our other languages for Azure SDKs, we have only the environment_credential that works for both user and app registrations.

**Comment by simon-an** [comment]
Sorry i am not sure what you mean. If you look at the pr, it is implemented in the environment credential. I can rename the pr if that helps :)

**Comment by heaths** [comment]
> Sorry i am not sure what you mean. If you look at the pr, it is implemented in the environment credential. I can rename the pr if that helps :) Edit: Since this is my first contribution to this repo, i tried to stick as close to the current code as possible.

You added a public (`WorkloadIdentityCredential`](https://github.com/Azure/azure-sdk-for-rust/pull/1319/files#diff-2ad4468fd1fd66aac39f9410601f0b67dd7d796bf9a36db12c5b6a87c0b99d35) which we don't need or have in any other language. All support should be internal (however you choose to implement it) to the `EnvironmentCredential`.

**Review by heaths — APPROVED** [review]

**Comment by demoray** [comment]
First, thank you for the contribution.

While the Azure SDK for Rust is not yet an official SDK, we do our best to follow the [Azure SDK development guidelines](https://azure.github.io/azure-sdk/general_introduction.html).

One of the principles we take to heart for this SDK is consistency across all of the SDKs.  We would prefer future contributions to consider this and other principles set forth in the above guidelines.

**Pull request merged**
