### PR TITLE
rename operation configuration to OperationConfig

### PR DESCRIPTION
**Pull request by ctaggart**
This gives a more description type title and solves a couple of name conflicts. Fixes https://github.com/ctaggart/autorust/issues/65. Adds 7 mgmt services for a total of 107.

### CODE REVIEW

**Comment by ctaggart** [comment]
maintenance, mysql, postgresql, keyvault, batch, softwareplan, azure-kusto

**Comment by rylev** [comment]
FYI: I'm not sure I like this. I've left a comment on the autorust repo as to why: https://github.com/ctaggart/autorust/issues/65#issuecomment-713542416

**Comment by ctaggart** [comment]
@rylev, I responded there with some more details. I removed use of `crate::*`, given your feedback in c607d2c. I'd like to merge this.

**Review by rylev — APPROVED** [review]
Ok I'm fine with this change then. I'm not sure how I feel specifically about the name `OperationConfig`, but we can go with it for now.

**Pull request merged**
