### PR TITLE
add 5 mgmt services: cosmos_db, healthcareapis, machinelearning, redis, redisenterprise

### PR DESCRIPTION
**Pull request by ctaggart**
Now that https://github.com/ctaggart/autorust/pull/78 is fixed.

### CODE REVIEW

**Comment by ctaggart** [comment]
CI failed once with: :-/
```
 LLVM ERROR: IO failure on output stream: No space left on device
error: could not compile `azure_key_vault`.
```

**Comment by rylev** [comment]
@ctaggart I'm guessing we run out of disk space? This is a tough one to fix as I don't believe we can increase that... We may have to break up the workspace...

**Comment by ctaggart** [comment]
@rylev, yes we were running out of disk space. Solved in #70.

**Review by heaths — APPROVED** [review]
Only glanced through it based on offline conversation.

**Pull request merged**
