### PR TITLE
Add Microsoft Fabric cloud location

### PR DESCRIPTION
**Pull request by kevinzwang**
Microsoft Fabric uses a different endpoint from the Azure cloud, this PR adds support for this endpoint.

### CODE REVIEW

**Comment by kevinzwang** [comment]
@microsoft-github-policy-service agree

**Review by heaths — CHANGES_REQUESTED** [review]
@seanmcc-msft does this change seem appropriate for Storage, or any service? We don't have a Service Fabric endpoint for any other language, and I'm surprised to see a fixed domain but maybe that is valid for Storage at least?

**Comment by kevinzwang** [comment]
I'm not sure how this fits into other services, but it's just something I noticed was missing from the storage API compared to the [`object_store`](https://crates.io/crates/object_store) crate: https://github.com/apache/arrow-rs/blob/035b5899f3198cbbdddc772f64c214332e6323fe/object_store/src/azure/builder.rs#L846-L849

**Comment by heaths** [comment]
`main` branch has been moved to `legacy`. Closing old PRs that don't seem to meet the criticality bar. If you disagree, please reopen or switch to official, supported crates from `main` once available.

**Pull request closed without merging**
