### PR TITLE
Lean request builders

### PR DESCRIPTION
**Pull request by rylev**
This PR further reduces the boiler plate required in request builders. By removing the type level checking of required fields. Instead any required fields must be supplied on construction. This is just as verifiably correct as the previous version but it dramatically reduces the amount of boiler plate. For example, in `create_collection_builder.rs`, the  number of lines of code was more than halved. 

This does impact the consumer of this crate in the following way:

**Before**
```rust
 client
    .create_collection()	               
    .with_collection_name(&COLLECTION)	
    .with_offer(Offer::Throughput(400))	
    .with_indexing_policy(&ip)	
    .with_partition_key(&("/id".into()))
```

**After**
```rust
client.create_collection(Offer::Throughput(400), &COLLECTION, &ip, &("/id".into()))
```

The new approach is certainly shorter though it is not quite as self documenting as before. Documentation, plus However, the type that is produced from `create_collection` is certainly much clearer now than before:

**Before**
```rust 
CreateCollectionBuilder<'a, No, No, No, No> 
```

**After**
```rust
CreateCollectionBuilder<'a>
```

I've set this as a draft PR since I've only done one of the builders, but I wanted to collect feedback first, especially from @MindFlavor.

### CODE REVIEW

**Comment by MindFlavor** [comment]
I am strongly against this solution. 
The builder pattern is safe and easy to use. It supports mandatory and optional fields. It works **very** well with autocompletion.

Putting everything in the constructor is an antipattern. There is a clippy lint for this. It's called  `too_many_arguments`. Quoting from the clippy docs:

> ### Why is this bad
> Functions with lots of parameters are considered bad style and reduce readability (“what does the 5th parameter mean?”). 
> Consider grouping some parameters into a new type.

## Example

For example, `replace document` has 9 parameters (2 of witch are mandatory). With the actual calling convention it is: 

```rust
let replace_document_response = collection_client
   .replace_document()
   .with_document_id(&doc.document.id)
   .with_partition_keys(&(&doc.document.id).into())
   .with_if_match_condition(IfMatchCondition::Match(&document.etag))
   .execute_with_document(&doc)
   .await?;
```

This code is easy to write and, most importantly, very easy to read. 
I can immediately understand that the code:

1. Replaces a document.
2. Using a specific document id.
3. Using specific partition keys.
4. Only if the match condition is met.

Putting everything in the constructor becomes: 

```rust
 let replace_document_response = collection_client
   .replace_document(
      &doc.document.id,
      (&(&doc.document.id).into()),
      None,
      None,
      Some(IfMatchCondition::Match(&document.etag)),
      None,
      None,
      None,
      None,
   )
   .execute_with_document(&doc)
   .await?;
```

This is troublesome in so many ways:

1. What is `(&(&doc.document.id).into())`? I have to look it up at the docs. 
2. What are the `None`? I have - again - to look at the docs. I also have to count the position of the arguments.
3. I have to use `Some` which is unnecessarily verbose. 

We could use the constructor only for the mandatory fields (the object oriented approach, a la C#) and it becomes:

```rust
 let replace_document_response = collection_client
   .replace_document(
      &doc.document.id,
      (&(&doc.document.id).into()),     
   )
   .with_if_match_condition(IfMatchCondition::Match(&document.etag))
   .execute_with_document(&doc)
   .await?;
```

It's better but I still do not have a clue of what ` (&(&doc.document.id).into())` means. 

So from an usability perspective it would be a **huge** loss.

### Type produced

`CreateCollectionBuilder<'a, No, No, No, No>` is unseemly, I agree. The point is that the user does not see this. It's an internal struct, never to be manually constructed. We could change it in `CreateCollectionBuilder_NoFields<'a>`, `CreateCollectionBuilder_DocId<'a>`, etc... if we don't like the generics and the phantom types. 
But since the user won't see them anyway so it's a moot point IMHO.

### Boilerplate

This is an issue. No, scratch that, this is **the** issue. The amount of boilerplate is staggering. My code generator leaves a lot to be desired and cannot be easily automated. This is the pain point we should address 👍. 
I think @ctaggart has a lot of experience in this area, maybe he could help us create a macro that does the same thing in a fraction of the code. I am not familiar with procedural macros but I'm sure it could be done. And once done it can be reused everywhere.  It's a win-win solution.

So let's not worsen the UX of the crate for the sake of maintainer friendliness. Let's find a solution that improves maintainer happiness while keeping the API safe and easy to use.

**Comment by rylev** [comment]
This is why I made this PR early, because I figured it would elicit a strong response. 😊 I'm happy to work through these issues together.

### The example

The example you provide is not actually what I'm proposing. The constructor will _only_ take the required arguments. The optional arguments would still only be accessible through the setter methods as they currently are. So the first block of code is not what I'm proposing at all as I agree it is an anti-pattern. Your second code block in the example, is exactly what I'm proposing. 

While I agree that it is worse not as nice that the arguments aren't explicitly named, documentation and IDE infrastructure like rust-analyzer should make this relatively obvious. All function's in Rust work like this, and I don't buy that this situation is somehow different.

As for what `&(&doc.document.id).into()` actually is, I agree that it's not obvious from the code here, but this is something the user can easily make clearer by putting it into a named binding like `partition_keys`. I disagree that this is a *huge* loss, as this is how function calls always work in Rust and not every function takes a builder struct instead of separate arguments. 

### Too many arguments

Clippy's too many argument lint starts with 7 arguments, I don't believe this proposal would ever trigger that lint.

### Types produced

The types produced will be seen by end users as these are the exact types that show up in documentation. The user will see that `create_collection` returns a `CreateCollectionBuilder<'a, No, No, No, No>` and be very confused by what all the `No`s are. Believe me as I was recently very confused by this, and only learned how it worked by looking at the implementation. I think such a pattern has some use, but it's not worth the extra complexity cost in this case. 

Here's what my VS Code shows me in one of the Cosmos examples:
image

### Boilerplate

I disagree that this issue is only about maintainer ease and decreasing boilerplate. I believe the greatest benefit to this change would be discoverability in docs as this eliminates a _lot_ of generics which make the API much harder to understand. I think having a proc_macro that produces the same code that exists right now would not actually solve the issue at hand which is generally an issue of complexity _not_ boiler plate.

**Comment by MindFlavor** [comment]
You make valid points, especially the one about VSCode (I use Vim and the autocompletion there is much easier to follow)

image

Let me answer to one of your concerns:

> The types produced will be seen by end users as these are the exact types that show up in documentation. The user will see that create_collection returns a CreateCollectionBuilder<'a, No, No, No, No> and be very confused by what all the Nos are.

The `No` list is a shortcoming of the actual implementation. It does not have to be that way: we could/should use more meaningful names. 
For example, instead of having `ReplaceDocumentBuilder<'a, No, No>` we could have `ReplaceDocumentBuilder<'a, DocumentIdMissing, PartitionKeysMissing>` which conveys more clearly what's missing.

Or, instead of a generic `CreateCollectionBuilder<'a, No, No, No, No>` we could have `CreateCollectionBuilder<'a, NameMissing, OfferMissing, IndexingPolicyMissing, PartitionKeyMissing>`. This is much cleaner.
It's very verbose but you will see the types updating themselves automatically as soon as you specify the relative field. So if you call `with_offer()` you will see `CreateCollectionBuilder<'a, NameMissing, OfferSet, IndexingPolicyMissing, PartitionKeyMissing>` (which I think it would be neat).

That said I understand that I have a CS approach that may not be appealing to most devs. If you think we would attract more people with a constructor-based approach we should definitely switch to that.

**Comment by rylev** [comment]
I don't think the pattern in question is a bad pattern in general. I just don't think it's worth the required boiler plate nor is it strictly better in this particular case. Forcing the user to supply required arguments at the original call to `create_collection` is the "normal" way, and is thus more discoverable without really being any more error prone. 😊

**Comment by rylev** [comment]
Closing this since we decided to stick with the infallible builder pattern. This should need much less boiler plate when const generic stabilize.

**Pull request closed without merging**
