### PR TITLE
Set default values for blob properties on deserialization

### PR DESCRIPTION
**Pull request by ArtemTrofimushkin**
Fixes https://github.com/Azure/azure-sdk-for-rust/issues/261

### CODE REVIEW

**Comment by heaths** [comment]
Thank you for the PR, but rather than allocate new strings for clearly optional content, shouldn't these be `Option<String>` and, thus, default to `None`? This is how our SDKs work in other languages.

/cc @rylev @ctaggart

**Comment by ctaggart** [comment]
Correct, if they are optional, they should be mapped as `Option<String>`.

**Comment by ArtemTrofimushkin** [comment]
@heaths @ctaggart 
Thanks for comments, I fixed that

**Review by heaths — APPROVED** [review]

**Comment by heaths** [comment]
@ArtemTrofimushkin thanks for the update. Looks like `fmt` doesn't like line breaks when a single method call is used (broken build).

**Comment by heaths** [comment]
Seems I can't update the PR to contribute a patch, but perhaps this will help:
```diff
commit adffa7dd79bbdf05e098c3b6344f7ed792a1e8bd
Author: Heath Stewart <heaths@microsoft.com>
Date:   Fri May 28 10:33:41 2021 -0700

    Fix formatting

diff --git a/sdk/storage/src/blob/blob/mod.rs b/sdk/storage/src/blob/blob/mod.rs
index 069c3188..0fb6debb 100644
--- a/sdk/storage/src/blob/blob/mod.rs
+++ b/sdk/storage/src/blob/blob/mod.rs
@@ -208,22 +208,18 @@ impl Blob {
             .parse::<BlobType>()?;
         trace!("blob_type == {:?}", blob_type);
 
-        let content_encoding = h
-            .get_as_string(header::CONTENT_ENCODING);
+        let content_encoding = h.get_as_string(header::CONTENT_ENCODING);
         trace!("content_encoding == {:?}", content_encoding);
 
-        let content_language = h
-            .get_as_string(header::CONTENT_LANGUAGE);
+        let content_language = h.get_as_string(header::CONTENT_LANGUAGE);
         trace!("content_language == {:?}", content_language);
 
         let content_md5 = h.get_as_string(CONTENT_MD5).unwrap_or_else(String::new);
         trace!("content_md5 == {:?}", content_md5);
 
-        let cache_control = h
-            .get_as_string(header::CACHE_CONTROL);
+        let cache_control = h.get_as_string(header::CACHE_CONTROL);
 
-        let content_disposition = h
-            .get_as_string(header::CONTENT_DISPOSITION);
+        let content_disposition = h.get_as_string(header::CONTENT_DISPOSITION);
 
         let lease_status = h
             .get_as_enum(LEASE_STATUS)?
```

**Comment by ArtemTrofimushkin** [comment]
@heaths Fixed formatting

**Review by ctaggart — APPROVED** [review]

**Pull request merged**
